plugins {
    id 'java'
    id 'org.springframework.boot' version '4.0.1'
    id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.hunesion'
version = '0.0.1-SNAPSHOT'
description = 'Test-Demo-R2DBC'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-data-r2dbc'
    implementation 'org.springframework.boot:spring-boot-starter-webflux'
    implementation 'org.springframework.boot:spring-boot-starter-validation'

    implementation "org.springframework.boot:spring-boot-starter-hateoas"

    // JDBC only for Liquibase migrations
    implementation "org.springframework.boot:spring-boot-starter-jdbc"
    implementation "org.liquibase:liquibase-core"
    runtimeOnly "org.postgresql:postgresql"
    implementation "com.zaxxer:HikariCP"

    implementation "org.mapstruct:mapstruct:1.5.5.Final"
    annotationProcessor "org.mapstruct:mapstruct-processor:1.5.5.Final"
    annotationProcessor "org.projectlombok:lombok-mapstruct-binding:0.2.0"

    implementation "org.postgresql:r2dbc-postgresql"
    implementation "org.apache.commons:commons-lang3"
    implementation "com.fasterxml.jackson.datatype:jackson-datatype-jsr310"

    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
    testImplementation 'org.springframework.boot:spring-boot-starter-data-r2dbc-test'
    testImplementation 'org.springframework.boot:spring-boot-starter-webflux-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
    useJUnitPlatform()
}
