services:
  ansible:
    build:
      context: ./ansible-control
      dockerfile: Dockerfile
    container_name: ansible
    volumes:
      - ./ansible:/work
    working_dir: /work
    environment:
      - ANSIBLE_HOST_KEY_CHECKING=False
      - ANSIBLE_RETRY_FILES_ENABLED=False
    stdin_open: true
    tty: true
