services:
  ansible:
    build: ./ansible-control
    container_name: ansible-control
    volumes:
      - ./ansible:/work
    working_dir: /work
    depends_on:
      - target1
      - target2
    tty: true

  target1:
    image: ubuntu:24.04
    container_name: target1
    command: >
      bash -lc "
        apt-get update &&
        apt-get install -y openssh-server sudo &&
        useradd -m -s /bin/bash dev &&
        echo 'dev ALL=(ALL) NOPASSWD:ALL' > /etc/sudoers.d/dev &&
        mkdir -p /home/dev/.ssh &&
        chmod 700 /home/dev/.ssh &&
        cat /tmp/id_ed25519.pub > /home/dev/.ssh/authorized_keys &&
        chmod 600 /home/dev/.ssh/authorized_keys &&
        chown -R dev:dev /home/dev/.ssh &&
        mkdir -p /run/sshd &&
        /usr/sbin/sshd -D
      "
    volumes:
      - ./ansible/key/id_ed25519.pub:/tmp/id_ed25519.pub
    ports:
      - "2221:22"

  target2:
    image: ubuntu:24.04
    container_name: target2
    command: >
      bash -lc "
        apt-get update &&
        apt-get install -y openssh-server sudo &&
        useradd -m -s /bin/bash dev &&
        echo 'dev ALL=(ALL) NOPASSWD:ALL' > /etc/sudoers.d/dev &&
        mkdir -p /home/dev/.ssh &&
        chmod 700 /home/dev/.ssh &&
        cat /tmp/id_ed25519.pub > /home/dev/.ssh/authorized_keys &&
        chmod 600 /home/dev/.ssh/authorized_keys &&
        chown -R dev:dev /home/dev/.ssh &&
        mkdir -p /run/sshd &&
        /usr/sbin/sshd -D
      "
    volumes:
      - ./ansible/key/id_ed25519.pub:/tmp/id_ed25519.pub
    ports:
      - "2222:22"
