- name: Change user password on targets
  hosts: targets
  become: true
  gather_facts: false

  vars:
    username: "demo"
    plain_password: "password"

  tasks:
    - name: Update user password
      ansible.builtin.user:
        name: "{{ username }}"
        password: "{{ plain_password | ansible.builtin.password_hash('sha512') }}"
        update_password: always
