[targets]
db-server-01 ansible_host=192.168.230.131 ansible_port=22 ansible_user=ebon ansible_password=168 ansible_become_password=123 ansible_become_method=su
db-server-02 ansible_host=192.168.230.132 ansible_port=22 ansible_user=halaha ansible_password=169 ansible_become_password=123 ansible_become_method=su